--- Running plotly.tools.FigureFactory.create_distplot#31YY/create_distplotYY, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'plotly.tools.FigureFactory.create_distplot#31YY'), ('notebook', 'create_distplotYY'), ('text', '')])
[INFO] This case is fully fixed!


real	0m1.811s
user	0m2.814s
sys	0m5.853s
