--- Running testing.assert_extension_array_equal#36NN/assert_extension_array_equalNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'testing.assert_extension_array_equal#36NN'), ('notebook', 'assert_extension_array_equalNN'), ('text', '  File "assert_extension_array_equalNN.py", line 5, in <module>\n    tm.assert_extension_array_equal(b,  c,  True,  None,  False,  False, rtol=1e-05, atol=1e-08)\nTypeError: assert_extension_array_equal() got multiple values for argument \'rtol\'\n')])
  File "assert_extension_array_equalNN.py", line 5, in <module>
Error inducing API short name: assert_extension_array_equal, line no: 5
Error inducing API fqn: pandas.testing.assert_extension_array_equal, line no: 5
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'rtol', 'atol']
Prev Params: None
Prev Repair Action: None
Line No: 5
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'rtol', 'atol']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'IMPLICIT_2', 'IMPLICIT_3', 'IMPLICIT_4', 'IMPLICIT_5', 'rtol', 'atol']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.633s
user	0m1.630s
sys	0m5.784s
