--- Running tf.keras.layers.LocallyConnected2D#12YY/LocallyConnected2DYY, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'tf.keras.layers.LocallyConnected2D#12YY'), ('notebook', 'LocallyConnected2DYY'), ('text', '')])
[INFO] This case is fully fixed!


real	0m1.073s
user	0m2.168s
sys	0m6.057s
