--- Running scipy.optimize.fmin_cobyla#47NN/fmin_cobylaNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'scipy.optimize.fmin_cobyla#47NN'), ('notebook', 'fmin_cobylaNN'), ('text', '  File "fmin_cobylaNN.py", line 13, in <module>\n    result = fmin_cobyla(objective,  x0, cons=constraints, args=(), consargs=None, rhobeg=rhobeg, rhoend=rhoend, iprint=iprint, maxfun=maxfun)\nTypeError: fmin_cobyla() got an unexpected keyword argument \'iprint\'\n')])
  File "fmin_cobylaNN.py", line 13, in <module>
Error inducing API short name: fmin_cobyla, line no: 13
Error inducing API fqn: scipy.optimize.fmin_cobyla, line no: 13
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'IMPLICIT_1', 'cons', 'args', 'consargs', 'rhobeg', 'rhoend', 'iprint', 'maxfun']
Prev Params: None
Prev Repair Action: None
Line No: 13
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'IMPLICIT_1', 'cons', 'args', 'consargs', 'rhobeg', 'rhoend', 'iprint', 'maxfun']
EXPP: ['IMPLICIT_0', 'IMPLICIT_1', 'cons', 'args', 'consargs', 'rhobeg', 'rhoend', 'iprint', 'maxfun']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.596s
user	0m1.700s
sys	0m5.863s
