--- Running Response#18NN/ResponseNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'Response#18NN'), ('notebook', 'ResponseNN'), ('text', '  File "ResponseNN.py", line 2, in <module>\n    Response(1, headers=None, text=None, request=None, ext=None, html=None, json=None, content=None, stream=None)\nTypeError: __init__() got an unexpected keyword argument \'ext\'\n')])
  File "ResponseNN.py", line 2, in <module>
Error inducing API short name: Response, line no: 2
Error inducing API fqn: httpx.Response, line no: 2
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: ['IMPLICIT_0', 'headers', 'text', 'request', 'ext', 'html', 'json', 'content', 'stream']
Prev Params: None
Prev Repair Action: None
Line No: 2
Prev Line No: 0
GitHub Candidates:
[]
KP:['IMPLICIT_0', 'headers', 'text', 'request', 'ext', 'html', 'json', 'content', 'stream']
EXPP: ['IMPLICIT_0', 'headers', 'text', 'request', 'ext', 'html', 'json', 'content', 'stream']
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.438s
user	0m0.397s
sys	0m0.042s
