--- Running client.send#4NN/sendNN, strategy: relancer
[ERR MSG]: OrderedDict([('project', 'client.send#4NN'), ('notebook', 'sendNN'), ('text', '  File "sendNN.py", line 6, in <module>\n    client.send(request, allow_redirects=USE_CLIENT_DEFAULT)\nTypeError: send() got an unexpected keyword argument \'allow_redirects\'\n')])
  File "sendNN.py", line 6, in <module>
Error inducing API short name: send, line no: 6
Error inducing API fqn: UNKNOWN, line no: 6
*** TypeError: PLACEHOLDER
Repair Action: arg_name
Key Params: []
Prev Params: None
Prev Repair Action: None
Line No: 6
Prev Line No: 0
GitHub Candidates:
[]
KP:[]
EXPP: []
APIDoc Candidates:
[]
All Solution Candidates:
[]
[INFO] This case cannot be fixed!


real	0m0.448s
user	0m0.404s
sys	0m0.044s
